TypeError: 'OSError' object is not subscriptable raised when terminate senlin-api process unexpectedly
When terminate senlin-api process the `evenlet.wsgi.server` raised OSError exception that is not a list or a tuple which make TypeError raised and the senlin-api process may not be terminated properly

Closes-Bug: #2047914
Change-Id: Id02befe51e9118c8d8dafc3c926398fbf7e1258e